### ISSUE TITLE
[Client-Side] Solve jsonError when writing accented letters

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#13]
Handle jsonError invalid UTF-8 byte

**Comment by emancus** [comment]
You can try this solution!

char test[]="èÈà";
CharToOemBuffA(test,test,sizeof(test)); //Do a in-place conversion of the string "test" to the codepage OEM.
cout<<test;

For use the CharToOemBuffA function, you have to include the following library:
#include <windows.h>	//Necessary CharToOemBuffA
#include <winuser.h>

**Comment by HidroSaphire** [comment]
I've try this one, but it doesn't work

`QString filename = text;
QByteArray ba_filename = filename.toLocal8Bit();
const char *c_filename = ba_filename.data();
**QString qstr2 = QString::fromLocal8Bit(c_filename);**
...
_client->setFilename(qstr2);`

**Comment by emancus** [comment]
### Solved by using 
- `QLatin1String(MYSTRING.toUtf8())`  when send
- `MYSTRING.toLatin1()`                       when received
