### ISSUE TITLE
UserProfile from MenuWindow gives error if a user has no file

### ISSUE THREAD

**Issue by rinaldoclemente** [giovannic96/Real-time-collaborative-text-editor#149]
When the button Profile is clicked and user has no file (own files and coll files) the server gives the error "Non hai ancora creato un documento!"

**Comment by HidroSaphire** [comment]
Something happens! Isn't like that before!

**Comment by HidroSaphire** [comment]
![fhesuifhehfhes](https://user-images.githubusercontent.com/55850895/77093041-bb21e780-6a0a-11ea-9f60-b1bec8bcc53d.png)

@rinaldoclemente i got no error when I click upon profile with a new user (without document).
I close this issue and lable it as "bad issue". If you get this error again, reopen this issue and tag me!
