### ISSUE TITLE
[Client-Side] Remove exitButton

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#16]
Remove exitButton on top-right of these windows:
menuWindow(0)
menuWindow(1)

Also remove logoutButton in this window:
menuWindow(1)

**Comment by emancus** [comment]
The exitButton on top-right have now the function of close the entire application. The user is disconnected at the click of the button and then the application is closed
The logoutButton have a similiar function, but the user will return to StartWindow.
