### ISSUE TITLE
In editorWindow, letter 'z' has another appearance

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#47]
Letter 'z' has another appearance with respect to the other letters

**Comment by emancus** [comment]
@giovannic96 is a different Ascii code or is a different font used for the 'z' letter? Is in the title of the document or is in the RealTextEdit?

**Comment by giovannic96** [comment]
In the realtextedit

**Comment by emancus** [comment]
I can't see any visual difference. There aren't differences even comparing the "z" of TextEdit to the "z" of the character map of the Time New Roman. I also tried different characters and I don't see any differences. 

Screenshot in the attachment and I close this issue as "bad issues".

![z-things](https://user-images.githubusercontent.com/55850895/69674145-229eda80-109c-11ea-8fea-d89b67fb62e2.png)

**Comment by giovannic96** [comment]
![err](https://user-images.githubusercontent.com/22454405/70248043-a599f200-177a-11ea-9ff2-76cd4c622e10.PNG)

**Comment by emancus** [comment]
![issue](https://user-images.githubusercontent.com/55850895/70388617-87b7d180-19b4-11ea-98f3-3ded098c8b46.png)

Check again, there aren't no differences (starting to write on the editor without changing anything). I belive is your local problem. Check your font map. Closed until more details.

**Comment by giovannic96** [comment]
My font map is correct. Now I will show you two pictures: the first one is Microsoft Word editor and here as you can see there aren't any problems with letter 'z', in fact it is displayed correctly for each font size.
The second picture represents our Carte Editor, and here as you can see there are problems with letter 'z', in particular for small font sizes, ex. 14 or 12 (while 16, 18,etc. are ok). 
So it is not a problem of my font map. 
Try to fix this 

WORD
![word](https://user-images.githubusercontent.com/22454405/70852531-9fa2c000-1ea2-11ea-9ab5-a479545d80a8.PNG)

CARTE
![carte](https://user-images.githubusercontent.com/22454405/70852534-a92c2800-1ea2-11ea-91da-1ce8ed9906d5.PNG)

**Comment by emancus** [comment]
I've cleary understand the issues. I need to test it on your local computer ASAP.
