### ISSUE TITLE
[Client-Side] accented letters

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#48]
![Cattura](https://user-images.githubusercontent.com/22454405/69587922-51a74480-0fe7-11ea-8d1d-8c8a0fd10eeb.PNG)

I choose "jkè" as filename. The "è" is seen as "?" as you can see in the above picture

**Comment by emancus** [comment]
Strange, I fixed this problem (See issue #13) and ran several tests (without error) just two days ago. I will personally conduct some investigation on this.

**EDIT:**
_Reported as a bad issue and closed until further reports. If necessary, reopen this or issue #13_
