### ISSUE TITLE
[Server-Side] Transmission of letters happens also for different files

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#49]
If I try to write in a filename "file1" with the client1 and in the meanwhile the client2 has another file opened in his/her editor, letters written by client1 are inserted also in editor of client2! Big error!
They can edit only the ones that are in collaboration with

**Comment by emancus** [comment]
Maybe it's beacusa of "current file: URI1" is selected on the Server and it is changed when someother create a new document?
