### ISSUE TITLE
[Client-Side] Fix menu bar (IMPORTANT, high priority)

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#50]
Fix menu bar, scrooling, resizing window and a strange behaviour (editor window moves around) when click on the label that changes the font

**Comment by emancus** [comment]
Is a Well-Know Bug. We have already two branches opened that fix this problem somehow, but it is a complex work to adapt it to the Editor Interface. Being also primarily an aesthetic and non-functional issue of the editor, we (Me and @rinaldoclemente) decided to work on it later as a result of the implementation of some basic editor functionality.

**Comment by fr2sinc** [comment]
<img width="606" alt="Bug_navbar" src="https://user-images.githubusercontent.com/56112029/69716598-a0013400-110a-11ea-8cf6-6d3f239c0d7b.PNG">

Furthermore the menu buttons in the menu bar overlap each other, when using more than 100% zoom

**Comment by giovannic96** [comment]
According to me, this menu bar it's the most important bug to solve for the next saturday because it's about editor graphics

**Comment by giovannic96** [comment]
If we are not able to handle this, try to switch ASAP to the window normal bar

**Comment by emancus** [comment]
We are able but isn't a snap of fingers. We had to reengineering the layout, and is a WIP.
Due to yesterday's mess, it is a postponed task.
