### ISSUE TITLE
Solve Well-Known QTBUG-53022 for High DPI Monitor

### ISSUE THREAD

**Issue by emancus** [giovannic96/Real-time-collaborative-text-editor#56]
I tryed some solution in main.cpp (copied also in the constructor of EditorWindow), but nothing happend!
See this for futhermore info https://bugreports.qt.io/browse/QTBUG-53022

**Comment by emancus** [comment]
I can't do it. I've tried so hard, but there is no solution due deadline! Nobody cares!

**Comment by rinaldoclemente** [comment]
https://github.com/giovannic96/Real-time-collaborative-text-editor/commit/43faee3c31cae617303d1acf262ccc16d1023bc6
