### ISSUE TITLE
[Client-Side] Icon bar at the bottom works only when opening file, not when creating new file

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#58]
The icon bar at the bottom (for editor window) is created if I open the file, but if I try to create a new file, the icon at the bottom is not created(i.e. it doesn't exist)

**Comment by emancus** [comment]
Did you mean the Window's TaskBar?

**Comment by giovannic96** [comment]
> Did you mean the Window's TaskBar?

yes the icon in the taskbar at the bottom
