### ISSUE TITLE
[Client-Side] Strange spaces after filename in listfile window 

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#60]
Maybe this happens if a filename is large.
See picture below (last line)

![error](https://user-images.githubusercontent.com/22454405/70246518-2f948b80-1778-11ea-880d-ad765bda7656.PNG)

**Comment by emancus** [comment]
Ok, I will fix this

**Comment by emancus** [comment]
![issue](https://user-images.githubusercontent.com/55850895/70388905-6953d500-19b8-11ea-8770-63f6fddc5982.png)

Fixed in Daily 1273
