### ISSUE TITLE
Missing handle of some basic shortcut

### ISSUE THREAD

**Issue by emancus** [giovannic96/Real-time-collaborative-text-editor#94]
Some basic shortcut like CLTR+Z (Undo) or CTRL+Maiusc+Z (Redo) can't work on Multi Client because there's no handle of Redo and Undo action

**Comment by giovannic96** [comment]
Can we use CTRL-Y instead of CTRL-Maiusc-Z? @HidroSaphire

**Comment by giovannic96** [comment]
I don't know if we have to implement it. It's not strictly written in the requirements. We can handle this situation later.

**Comment by giovannic96** [comment]
Do we have to insert also for example CTRL-I (italic), CTRL-B (bold), and so on?

**Comment by emancus** [comment]
Ok, I can do it (if we had time left).
Yes, cause the QTextEdit have this behaviour of default
