### ISSUE TITLE
Multiple selection and deletion by pressing a letter not working properly

### ISSUE THREAD

**Issue by giovannic96** [giovannic96/Real-time-collaborative-text-editor#98]
When selecting text (ex. 4 letters), and then pressing a letter, in the other client the 4 letters aren't deleted

**Comment by giovannic96** [comment]
Consider also the case in which chars are bold, underline, etc.

**Comment by emancus** [comment]
Tip: maybe we can handle with an event... 
something like (in pseudo-code):
```
if(cursor.hasSelection()){
   if( "letter X is pressed" ){   //or switchcase
       delete selection;
       insert letter X //also the spacebar is a letter
   }else if("backslash is pressed"){
       delete selection
   }
}
```
I can work on it if you want.
